### ISSUE TITLE
What should I do if I want to use my own datasets?

### ISSUE THREAD

**Issue by haprine** [zhangbq-research/Prototype_Completion_for_FSL#10]
Thanks for your interesting work. I wonder what should I do if I want to replace the miniImagenet by my own datasets? Should I transform my own datasets into pickle or I have to do something else to my datasets? I'll appreciate it if you could reply. Thanks a lot.

**Comment by zhangbq-research** [comment]
Thank you very much for your attention to our work!
The above two methods can all achieve your goal:
1) transform your dataset to pickle file by using the package of PIL;
2) revise the file of dataset, e.g., revising the self.data as a list of file path and adding a row code to read picture in __getitem__

**Comment by haprine** [comment]
Got it , thanks again!
