### ISSUE TITLE
how to get the relationship between synsets_ids and labels on tiered-imagenet

### ISSUE THREAD

**Issue by 541124010** [zhangbq-research/Prototype_Completion_for_FSL#5]
The tiered-imagenet dataset I downloaded  has synset.txt and class_names.txt, both have 1000 datas.But as I know, tiered-imagenet only has 608 categories ,so I didn't understand these two files means. And I dont' know how to get the relationship between Synsetids and labels on tiered-imagenet .On mini-imagenet,It's clear because we can get the relationship  through data_train['catname2label'], but there's no such data on tiered-imagenet.
If it is convenient, could you open source the code on other datasets? or just the part of data processing.

**Comment by zhangdoudou123** [comment]
> The tiered-imagenet dataset I downloaded has synset.txt and class_names.txt, both have 1000 datas.But as I know, tiered-imagenet only has 608 categories ,so I didn't understand these two files means. And I dont' know how to get the relationship between Synsetids and labels on tiered-imagenet .On mini-imagenet,It's clear because we can get the relationship through data_train['catname2label'], but there's no such data on tiered-imagenet. If it is convenient, could you open source the code on other datasets? or just the part of data processing.

Have you solved the problem？
